import { SidebarLink, ThemeType } from "@/types";
import { PATHS } from "./paths";

export const themes: ThemeType[] = [
  { value: "light", label: "Светлая", icon: "/assets/icons/sun.svg" },
  { value: "dark", label: "Темная", icon: "/assets/icons/moon.svg" },
  // { value: "system", label: "Системная", icon: "/assets/icons/computer.svg" },
];

export const sidebarLinks: SidebarLink[] = [
  {
    imgURL: "/assets/icons/home.svg",
    route: PATHS.HOME,
    label: "Главная",
  },
  {
    imgURL: "/assets/icons/users.svg",
    route: PATHS.COMMUNITY,
    label: "Сообщество",
  },
  {
    imgURL: "/assets/icons/star.svg",
    route: PATHS.COLLECTION,
    label: "Избранное",
  },
  {
    imgURL: "/assets/icons/suitcase.svg",
    route: PATHS.JOBS,
    label: "Работа",
  },
  {
    imgURL: "/assets/icons/tag.svg",
    route: PATHS.TAGS,
    label: "Метки",
  },
  {
    imgURL: "/assets/icons/user.svg",
    route: PATHS.PROFILE,
    label: "Профиль",
  },
  {
    imgURL: "/assets/icons/question.svg",
    route: PATHS.ASK_QUESTION,
    label: "Задать вопрос",
  },
];

export const BADGE_CRITERIA = {
  QUESTION_COUNT: {
    BRONZE: 10,
    SILVER: 50,
    GOLD: 100,
  },
  ANSWER_COUNT: {
    BRONZE: 10,
    SILVER: 50,
    GOLD: 100,
  },
  QUESTION_UPVOTES: {
    BRONZE: 10,
    SILVER: 50,
    GOLD: 100,
  },
  ANSWER_UPVOTES: {
    BRONZE: 10,
    SILVER: 50,
    GOLD: 100,
  },
  TOTAL_VIEWS: {
    BRONZE: 1000,
    SILVER: 10000,
    GOLD: 100000,
  },
};

export const CURRENCY_NOTATIONS: { [key: string]: string } = {
  ALL: "Lek",
  AFN: "؋",
  ARS: "$",
  AWG: "ƒ",
  AUD: "$",
  AZN: "ман",
  BSD: "$",
  BYR: "p.",
  BZD: "BZ$",
  BMD: "$",
  BOB: "$b",
  BAM: "KM",
  BWP: "P",
  BGN: "лв",
  BRL: "R$",
  BND: "$",
  KHR: "៛",
  CAD: "$",
  KYD: "$",
  CLP: "$",
  CNY: "¥",
  COP: "$",
  CRC: "₡",
  HRK: "kn",
  CUP: "₱",
  CZK: "Kč",
  DKK: "kr",
  DOP: "RD$",
  XCD: "$",
  EGP: "£",
  SVC: "$",
  EEK: "kr",
  EUR: "€",
  FKP: "£",
  FJD: "$",
  GHC: "¢",
  GIP: "£",
  GTQ: "Q",
  GGP: "£",
  GYD: "$",
  HNL: "L",
  HKD: "$",
  HUF: "Ft",
  ISK: "kr",
  INR: "₹",
  IDR: "Rp",
  IRR: "﷼",
  IMP: "£",
  ILS: "₪",
  JMD: "J$",
  JPY: "¥",
  JEP: "£",
  KZT: "лв",
  KPW: "₩",
  KRW: "₩",
  KGS: "лв",
  LAK: "₭",
  LVL: "Ls",
  LBP: "£",
  LRD: "$",
  LTL: "Lt",
  MKD: "ден",
  MYR: "RM",
  MUR: "₨",
  MXN: "$",
  MNT: "₮",
  MZN: "MT",
  NAD: "$",
  NPR: "₨",
  ANG: "ƒ",
  NZD: "$",
  NIO: "C$",
  NGN: "₦",
  NOK: "kr",
  OMR: "﷼",
  PKR: "₨",
  PAB: "B/.",
  PYG: "Gs",
  PEN: "S/.",
  PHP: "₱",
  PLN: "zł",
  QAR: "﷼",
  RON: "lei",
  RUB: "руб",
  SHP: "£",
  SAR: "﷼",
  RSD: "Дин.",
  SCR: "₨",
  SGD: "$",
  SBD: "$",
  SOS: "S",
  ZAR: "R",
  LKR: "₨",
  SEK: "kr",
  CHF: "CHF",
  SRD: "$",
  SYP: "£",
  TWD: "NT$",
  THB: "฿",
  TTD: "$",
  TRY: "₤",
  TRL: "₤",
  TVD: "$",
  UAH: "₴",
  GBP: "£",
  USD: "$",
  UYU: "$U",
  UZS: "лв",
  VEF: "Bs",
  VND: "₫",
  YER: "﷼",
  ZWD: "Z$",
};
